version: '3'

services:
  mysql:
    image: mysql:8.0.34-debian
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: monitor_mall
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
